import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Home from "./page";
import Slidebar from "@/components/Slidebar/Slidebar";

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-gray-100">
        <Header />
        <div className="flex max-w-[1100px] mx-auto px-2 py-4">
          <Slidebar />
          {children}
          <div className="w-full"></div>
        </div>
      </body>
    </html>
  );
}
